version: '3.3'

services:
  mc_rtc_tutorials:
    # image: ghcr.io/isri-aist/mc_rtc_tutorials:latest
    user: root
    container_name: mc_rtc_tutorials
    environment:
      DISPLAY: $DISPLAY
    # Uncomment if you can to build local image
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Use the command 'echo $XAUTHORITY' to find exact path
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority

      - "../config:/root/config/"
      - "../controllers:/root/mc_rtc_ws/"
      - "../robots_description/:/root/colcon_ws/src/"
      - "./colcon_defaults.yaml:/root/colcon_ws/colcon_defaults.yaml"
      - "../robots/:/root/mc_robots/"
      - "../robots_interface/:/root/mc_interface/"
    privileged: True
    stdin_open: True
    command: bash
