MainRobot: UR5e
Enabled: [UrXLearning]
# Enabled: [Posture]
Timestep: 0.001

# Set a LogPolicy suitable for real-time
LogPolicy : threaded

# Interface specific parameters (mc_rtde)
RTDE:
  ControlMode: Position # Can be: Position/Velocity/Torque

  ur5e: # Name of the robot in the controller
    ip: "192.168.1.6"
    driver: "ur_rtde" # Can be: "ur_rtde" (>=CB3) or "ur_modern_driver" (<=CB2). Default: ur_rtde
    gripper: "robotiq_arg85"

  ur7e: # Name of the robot in the controller
    ip: "localhost"

  ur10: # Name of the robot in the controller
    ip: "localhost"
